/*
Team: 01
Members: 

	Diego Omar Gallegos Maldonado
	Axel Domingo Lara Parés

Query #1
Description:

This file contains 
	
	-The CREATE DATABASE sentence-
	-All the CREATE TABLE sentences needed in the project-


Creation date: 2021-03-11
*/


CREATE DATABASE SMedia;

GO

USE SMedia;

GO


CREATE TABLE [User](

[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[Nickname] VARCHAR(255) UNIQUE NOT NULL,
[Password] VARCHAR(255) NOT NULL,
[Email] VARCHAR(255) NOT NULL,
[Name] VARCHAR(255) NOT NULL,
[LastName] VARCHAR(255) NOT NULL,
[Picture] VARCHAR(255),
[RegisterDate] DATETIME NOT NULL,
[LastLogIn] DATETIME NOT NULL,
[Active] BIT NOT NULL DEFAULT 1
);

GO

CREATE TABLE [Community](

[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[Name] VARCHAR(255) NOT NULL,
[Color] VARCHAR(255) NOT NULL,
[Description] VARCHAR(255) NOT NULL,
[Picture] VARCHAR(255),
[CreationDate] DATETIME NOT NULL,
[OwnerId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[Active] BIT NOT NULL DEFAULT 1
);

GO

CREATE TABLE [Post](

[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[Content] VARCHAR(320) NOT NULL,
[CreationDate] DATETIME NOT NULL,
[AuthorId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[CommunityId] BIGINT FOREIGN KEY REFERENCES [Community](id) NOT NULL,
[LastPostId] BIGINT FOREIGN KEY REFERENCES [Post](id) NULL,
[Active] BIT NOT NULL DEFAULT 1
);

GO

CREATE TABLE [PostPicture](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[ServerPath] VARCHAR(255) NOT NULL,
[PostId] BIGINT FOREIGN KEY REFERENCES [Post](id) NOT NULL
);

GO

CREATE TABLE [Reaction](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[Type] TINYINT NOT NULL DEFAULT 1,
[UserId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[PostId] BIGINT FOREIGN KEY REFERENCES [Post](id) NOT NULL
);

GO

CREATE TABLE [Message](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[Content] VARCHAR(320) NOT NULL,
[SenderId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[ReceiverId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[Date] DATETIME NOT NULL
);

GO

CREATE TABLE [FollowedCommunity](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[FollowerId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[CommunityId] BIGINT FOREIGN KEY REFERENCES [Community](id) NOT NULL,
[DateOfFollow] DATETIME NOT NULL
);

GO

CREATE TABLE [FollowedUser](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[FollowerId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[FollowedId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[DateOfFollow] DATETIME NOT NULL
);

GO

CREATE TABLE [Viewed](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[UserId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[PostId] BIGINT FOREIGN KEY REFERENCES [Post](id) NOT NULL
);

GO

CREATE TABLE [FavoritePost](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[UserId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[PostId] BIGINT FOREIGN KEY REFERENCES [Post](id) NOT NULL
)
;

GO


/* UPDATE : 2021-05-21 */
DROP TABLE IF EXISTS [Message];

GO

ALTER TABLE [User]
DROP COLUMN Picture;

GO

CREATE TABLE [UserPicture](
[Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
[ServerPath] VARCHAR(255) NOT NULL,
[UserId] BIGINT FOREIGN KEY REFERENCES [User](id) NOT NULL,
[Active] BIT NOT NULL DEFAULT 1
);

GO